apiVersion: apps/v1
kind: Deployment
metadata:
    name: eks-bmi-calculator-deployment
    namespace: eks-bmi-calculator
    labels:
        app: eks-bmi-calculator-app
spec:
    replicas: 1
    selector:
        matchLabels:
            app: eks-bmi-calculator-app
    template:
        metadata:
            labels:
                app: eks-bmi-calculator-app
        spec:
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                                  - key: kubernetes.io/arch
                                    operator: In
                                    values:
                                        - amd64
                                        - arm64
            containers:
                - name: nginx
                  image: benoithubert/bmi-calculator:latest
                  ports:
                      - name: http
                        containerPort: 80
                  imagePullPolicy: IfNotPresent
            nodeSelector:
                alpha.eksctl.io/nodegroup-name: linux-nodes
